//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5456
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecentDoc.RecentDoc {
    using System.Web;
    using System.Text.RegularExpressions;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.Security;
    using Microsoft.SharePoint.Utilities;
    using System.Web.UI;
    using System;
    using Microsoft.SharePoint.WebControls;
    using System.Web.UI.WebControls;
    using System.Collections.Specialized;
    using Microsoft.SharePoint;
    using System.Collections;
    using System.Web.Profile;
    using System.Text;
    using System.Web.Caching;
    using System.Configuration;
    using System.Web.UI.WebControls.WebParts;
    using System.Web.SessionState;
    using System.Web.UI.HtmlControls;
    
    
    public partial class RecentDoc {
        
        protected global::System.Web.UI.WebControls.Label Label1;
        
        public static implicit operator global::System.Web.UI.TemplateControl(RecentDoc target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControlLabel1() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.Label1 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "Label1";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControlTree(global::RecentDoc.RecentDoc.RecentDoc @__ctrl) {
            global::System.Web.UI.WebControls.Label @__ctrl1;
            @__ctrl1 = this.@__BuildControlLabel1();
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(@__ctrl1);
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__Render__control1));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__Render__control1(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {
            @__w.Write(@"
<style type=""text/css"">
    .container
    {
        width: 360px;
    }
    .container .content
    {
        float: left;
        width: 350px;
    }
    .container .right
    {
        float: left;
        width: 150px;
    }
    .container .row
    {
        margin-bottom: 10px;
    }
    .container .header
    {
        font-weight: bold;
    }
    .container .clear
    {
        clear: both;
        float: none;
    }
    .content span
    {
        font-weight: bold;
        font-size: 1.2em;
        color: #96172E;
    }
</style>
");
  
    try
    {
        System.Data.DataTable result = ViewState["Result"] as System.Data.DataTable;
        if (result != null && result.Rows.Count> 0)
        {

            @__w.Write(@"
<div class=""container"">
    <div class=""row header"">
        <div class=""content"">
            <span>What's New</span>
            <br />
            <br />
            Uploaded & updated documents during the last 30 days
        </div>
        
        <div class=""clear"">
        </div>
    </div>
    ");
       foreach (System.Data.DataRow row in result.Rows)
       {
            @__w.Write("\r\n    <div class=\"row\">\r\n        <div class=\"content\">\r\n            ");
              
                if (row["DocLink"].ToString().IndexOf(".pdf")> 0)
                {

            
            @__w.Write("\r\n            <a href=\"javascript:showDialog(\'");
                                    @__w.Write(row["DocLink"].ToString());

            @__w.Write("\')\">\r\n                \r\n                ");
        @__w.Write(row["Docname"].ToString());

            @__w.Write("\r\n            </a>\r\n            ");
              
                }
                else if (row["DocLink"].ToString().IndexOf(".ppt")> 0)
                {
            
            @__w.Write("\r\n            <a href=\"");
             @__w.Write( row["WebURL"] );

            @__w.Write("/_layouts/PowerPoint.aspx?PowerPointView=ReadingView&PresentationId=");
                                                                                                     @__w.Write(row["DocLink"].ToString());

            @__w.Write("&\">\r\n                \r\n                ");
        @__w.Write(row["Docname"].ToString());

            @__w.Write("\r\n            </a>\r\n            ");
              
                }
                else if (row["DocLink"].ToString().IndexOf(".xls")> 0 || row["DocLink"].ToString().IndexOf(".xlsx")> 0)
                {
            
            @__w.Write("\r\n            <a href=\"");
             @__w.Write( row["WebURL"] );

            @__w.Write("/_layouts/xlviewer.aspx?Id=");
                                                            @__w.Write(row["DocLink"].ToString());

            @__w.Write("&\">\r\n                \r\n                ");
        @__w.Write(row["Docname"].ToString());

            @__w.Write("\r\n            </a>\r\n            ");
              
                }
                else
                {
            
            @__w.Write("\r\n            <a href=\"");
             @__w.Write( row["WebURL"] );

            @__w.Write("/_layouts/WordViewer.aspx?id=");
                                                              @__w.Write(row["DocLink"].ToString());

            @__w.Write("&\">\r\n                \r\n                ");
        @__w.Write(row["Docname"].ToString());

            @__w.Write("\r\n            </a>\r\n            ");
              
                }

            
            @__w.Write("\r\n        </div>\r\n        \r\n        <div class=\"clear\">\r\n        </div>\r\n    </di" +
                    "v>\r\n    ");
       } 
            @__w.Write("\r\n</div>\r\n");
   }
        else
        { 
            @__w.Write("\r\n<div class=\"container\">\r\n    <ul>\r\n        <li>There is no documents available." +
                    " </li>\r\n    </ul>\r\n</div>\r\n");
   }
    }
    catch (Exception)
    {
    }

            parameterContainer.Controls[0].RenderControl(@__w);
        }
        
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
